"""Add username to server

Revision ID: 03b38ebfd87d
Revises: fe0e57b193ac
Create Date: 2020-09-09 22:12:09.946225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03b38ebfd87d'
down_revision = 'fe0e57b193ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('server', sa.Column('username', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('server', 'username')
    # ### end Alembic commands ###
