"""add vm

Revision ID: 0c244d93aa1e
Revises: 6a6a3de96b5b
Create Date: 2020-09-10 19:51:04.591895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c244d93aa1e'
down_revision = '6a6a3de96b5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('VM',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vmname', sa.String(length=20), nullable=True),
    sa.Column('server_id', sa.Integer(), nullable=True),
    sa.Column('vm_ip', sa.String(length=15), nullable=True),
    sa.Column('username', sa.String(length=20), nullable=True),
    sa.Column('identity_file', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['server_id'], ['server.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_VM_vm_ip'), 'VM', ['vm_ip'], unique=True)
    op.create_index(op.f('ix_VM_vmname'), 'VM', ['vmname'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_VM_vmname'), table_name='VM')
    op.drop_index(op.f('ix_VM_vm_ip'), table_name='VM')
    op.drop_table('VM')
    # ### end Alembic commands ###
