"""Add ServerConnection

Revision ID: 6a6a3de96b5b
Revises: 03b38ebfd87d
Create Date: 2020-09-10 13:51:38.136726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a6a3de96b5b'
down_revision = '03b38ebfd87d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('serverinterface',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interface_name', sa.String(length=20), nullable=True),
    sa.Column('server_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['server_id'], ['server.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_serverinterface_interface_name'), 'serverinterface', ['interface_name'], unique=False)
    op.create_table('server_connection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('int1', sa.Integer(), nullable=True),
    sa.Column('int2', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['int1'], ['serverinterface.id'], ),
    sa.ForeignKeyConstraint(['int2'], ['serverinterface.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('ix_server_interface_interface_name', table_name='server_interface')
    op.drop_table('server_interface')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('server_interface',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('interface_name', sa.VARCHAR(length=20), nullable=True),
    sa.Column('server_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['server_id'], ['server.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_server_interface_interface_name', 'server_interface', ['interface_name'], unique=False)
    op.drop_table('server_connection')
    op.drop_index(op.f('ix_serverinterface_interface_name'), table_name='serverinterface')
    op.drop_table('serverinterface')
    # ### end Alembic commands ###
