"""server table, vm table

Revision ID: cbd86bafd14b
Revises: a66de15c99b2
Create Date: 2020-02-01 14:36:13.053472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbd86bafd14b'
down_revision = 'a66de15c99b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('server',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('server_name', sa.String(length=20), nullable=True),
    sa.Column('server_ip', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_server_server_ip'), 'server', ['server_ip'], unique=True)
    op.create_index(op.f('ix_server_server_name'), 'server', ['server_name'], unique=True)
    op.create_table('VM',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vm_name', sa.String(length=20), nullable=True),
    sa.Column('vm_control_ip', sa.String(length=15), nullable=True),
    sa.Column('server_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['server_id'], ['server.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_VM_vm_control_ip'), 'VM', ['vm_control_ip'], unique=True)
    op.create_index(op.f('ix_VM_vm_name'), 'VM', ['vm_name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_VM_vm_name'), table_name='VM')
    op.drop_index(op.f('ix_VM_vm_control_ip'), table_name='VM')
    op.drop_table('VM')
    op.drop_index(op.f('ix_server_server_name'), table_name='server')
    op.drop_index(op.f('ix_server_server_ip'), table_name='server')
    op.drop_table('server')
    # ### end Alembic commands ###
