"""add identity file

Revision ID: fe0e57b193ac
Revises: b9731305c762
Create Date: 2020-08-30 09:04:05.666478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe0e57b193ac'
down_revision = 'b9731305c762'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('server', sa.Column('identity_file', sa.String(length=40), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('server', 'identity_file')
    # ### end Alembic commands ###
